INSERT INTO `wk.tb_pedidos` (`ID_PEDIDO`,`ID_CLIENTE`,`VALOR`) VALUES (1,1,100.0000);

INSERT INTO `wk.tb_pedidos_itens` (`ID_PEDIDO_DETAIL`,`ID_PEDIDO`,`ID_PRODUTO`,`VALOR_UNITARIO`,`QUANTIDADE`) VALUES (1,1,1,2.3500,10.0000);
INSERT INTO `wk.tb_pedidos_itens` (`ID_PEDIDO_DETAIL`,`ID_PEDIDO`,`ID_PRODUTO`,`VALOR_UNITARIO`,`QUANTIDADE`) VALUES (2,1,2,3.2900,3.0000);
INSERT INTO `wk.tb_pedidos_itens` (`ID_PEDIDO_DETAIL`,`ID_PEDIDO`,`ID_PRODUTO`,`VALOR_UNITARIO`,`QUANTIDADE`) VALUES (3,1,3,7.9000,2.0000);
INSERT INTO `wk.tb_pedidos_itens` (`ID_PEDIDO_DETAIL`,`ID_PEDIDO`,`ID_PRODUTO`,`VALOR_UNITARIO`,`QUANTIDADE`) VALUES (4,1,4,3.9900,12.0000);
INSERT INTO `wk.tb_pedidos_itens` (`ID_PEDIDO_DETAIL`,`ID_PEDIDO`,`ID_PRODUTO`,`VALOR_UNITARIO`,`QUANTIDADE`) VALUES (5,1,5,1.3000,5.0000);
INSERT INTO `wk.tb_pedidos_itens` (`ID_PEDIDO_DETAIL`,`ID_PEDIDO`,`ID_PRODUTO`,`VALOR_UNITARIO`,`QUANTIDADE`) VALUES (6,1,6,9.9900,4.0000);
